### ISSUE TITLE
Autogenerate mapnik-config.bat

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik-gyp#1]
We need to have the gyp system auto-create mapnik-config.bat. Steps to get to this are:

  - Take the current `mapnik-config.bat` and turn it into a template like we do for mapnik-config for unix/with scons: https://github.com/mapnik/mapnik/blob/master/bin/mapnik-config.template.sh
  - Write GYP actions to call out to a script (preferably python) to read in the template and pass all the right variables (like library names, defines, etc).

Questions:

  - How should variables be passed from the `mapnik.gyp` file to the gyp action? As a bunch of command line args (quoting will be tricky) or maybe just serialize them to an intermediate json file. Then a python script could read that and combine with the template for the final result.

**Comment by springmeyer** [comment]
Noting that `TODO` is currently returned for `mapnik-config --git-describe` on windows due to this lacking feature. refs https://github.com/mapnik/node-mapnik/issues/73

**Comment by BergWerkGIS** [comment]
For future reference:
This is how it can be done in a batch file on Windows [`FOR /F "tokens=*" %%i in ('git describe') do SET GITVERSION=%%i`](https://github.com/mapnik/mapnik-gyp/blob/bdeb6f15c2d2438294894e77f3599824afc7e47d/package.bat#L8).

**Comment by BergWerkGIS** [comment]
done
