### ISSUE TITLE
DLL load failed when building mapnik

### ISSUE THREAD

**Issue by stefda** [mapnik/mapnik-gyp#10]
I've managed to install all dependencies but get the following error:

    Traceback (most recent call last):
      File "..\tests\visual_tests\test.py", line 5, in <module>
        import mapnik
      File "C:\dev\projects\mapnik-dependencies\packages\mapnik-master\bindings\python\mapnik\__init__.py", line 73, in <module
        from _mapnik import *
    ImportError: DLL load failed: The specified module could not be found.
    DONE building Mapnik
    ----------ERROR MAPNIK --------------
    !!!!!ERROR: ABORTED!!!!!!
    Started at  2:12:17.49, finished at  2:39:02.49
    -- DONE ---
    Started at  2:12:17.49, finished at  2:39:02.49

Might this be because I'm using VS 15 CTP instead of VS 14?

**Comment by BergWerkGIS** [comment]
Python bindings are now in their own repository:
https://github.com/mapnik/python-mapnik

No Windows support yet as of today.
