### ISSUE TITLE
map style rule based on OSM_ID it does not work

### ISSUE THREAD

**Issue by dumu2324** [mapnik/mapnik-gyp#11]
Hi all, 
I am using Mapnik in order to render OSM from Postgre/PostGIS  DB. 

My code is like this 

mapnik::feature_type_style road_blocked_style;
rule road_blocked_rule;  

road_blocked_rule.set_filter(parse_expression("[osm_id] = '61924590'")); 

stroke road_blocked_rule_stk(color(255,0,0), 3.0);
road_blocked_rule.append(line_symbolizer(road_blocked_rule_stk));
road_blocked_style.add_rule(road_blocked_rule); 
map.insert_style("road_blocked_style", road_blocked_style);

ISSUE: With the filter  parse_expression("[osm_id] = '61924590'"), there is no result! ( like no street with this ID would be found in the DB). But I am sure that the ID is valid. 

I have read that there has been issues with the convertion to BIG INT type. 
I am using mapnik-v2.2.0. 

How could I solve this issue? Do you have any ideas?

Thank you in advance!

**Comment by springmeyer** [comment]
https://github.com/mapnik/mapnik-support/issues is the correct location for a question like this.
