### ISSUE TITLE
Better setup docs

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik-gyp#12]
7z is needed to run `package.bat` for example but we don't mention this in the readme.

**Comment by BergWerkGIS** [comment]
Done.
https://github.com/mapnik/mapnik-gyp/commit/960e7128b11b37ab24597fc25c4d6df94c8dbfc2

**Comment by BergWerkGIS** [comment]
Reopened!
We need better overall docs.

**Comment by BergWerkGIS** [comment]
7z is included in the tmp-bin download now.

Windows specific docs are can be found in https://github.com/mapbox/windows-builds
