### ISSUE TITLE
"heavy" files still built in parallel

### ISSUE THREAD

**Issue by lightmare** [mapnik/mapnik-gyp#25]
https://ci.appveyor.com/project/Mapbox/mapnik/build/1.0.582#L122
It was apparently compiling 3 files at once:
```
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\CL.exe ... /MP ...

... fatal error C1060: compiler is out of heap space (compiling source file ..\..\src\expression_grammar.cpp)
... fatal error C1060: compiler is out of heap space (compiling source file ..\..\src\transform_expression_grammar.cpp)
... fatal error C1060: compiler is out of heap space (compiling source file ..\..\src\css_color_grammar.cpp)
 
    0 Warning(s)
    3 Error(s)
```

The problem is likely that `msbuild /m:1` option limits only the number of processes msbuild spawns, but the compiler then forks itself: [/MP](https://msdn.microsoft.com/en-us/library/bb385193.aspx)

Also while you'll be looking into it, would it be possible to make the `/p:SelectedFiles=` more easily editable? I honestly have no idea whether it can be multiline, or whether you can use backticks to read the list from another file.

**Comment by BergWerkGIS** [comment]
> Also while you'll be looking into it, would it be possible to make the `/p:SelectedFiles=` more easily editable? I honestly have no idea whether it can be multiline, or whether you can use backticks to read the list from another file.

Haven't found a way to do it yet.
Would also prefer a more readable notation.

I've removed `/MP` which gets us past `compiler is out of heap space` but now the rest of the build is also single threaded, despite

```
m:%NUMBER_OF_PROCESSORS% ^
/p:BuildInParallel=true ^
```

And that might make us run into the time limit again.
I think its 40 minutes.
Took 38.5 minutes now:
https://ci.appveyor.com/project/Mapbox/mapnik/build/1.0.586

**Comment by lightmare** [comment]
I'm bad with ... what?! there's no emoji :bat: :scream_cat:  ... but maybe you could override the option before each step:
```bat
:: before building big files
IF DEFINED APPVEYOR SET CL=/MP1

:: before building the rest
IF DEFINED APPVEYOR SET CL=/MP
```

Maybe even use `msbuild /m:1` for both. From the description it looks like that option is intended for building projects (does that mean targets?) in parallel -- buf if targets have multiple sources (which most in mapnik do), and /MP (without number) forks as many CL.exe workers as it has processors, then perhaps there's no need for more than `/m:1` :grey_question:

**Comment by BergWerkGIS** [comment]
> `IF DEFINED APPVEYOR SET CL=/MP1`

Good idea.

As far as I understand the `msbuild` docs:

* `/m:<number>`: number of spawned `msbuild.exe`s, equals number of projects built in parallel
* `/p:BuildInParallel=true`: number of `cl.exe` spawned by each `msbuild.exe`. Maximum being `%NUMBER_PROCESSORS%` if the current project can be split accordingly.

For example: 4 CPUs and everything can be parallized -> results in 16 `cl.exe`s.
4 * `msbuild.exe` and 4 * `cl.exe` for each of those.

**Comment by BergWerkGIS** [comment]
It's already parallel without setting `/MP`.
e.g., notice `1>` and `2>`: https://ci.appveyor.com/project/Mapbox/mapnik/build/1.0.588#L147

**Comment by lightmare** [comment]
Aren't those `1>` and `2>` msbuild worker ids?

The first block in that build:
```
building heavy files first...
```
... uses `/m:1` and there's no `1>`. There's no `/MP` on the compiler line and it didn't run out of heap space.

Then the second block:
```
calling msbuild on mapnik-json and mapnik-wkt...
```
... uses `/m:%NUMBER_OF_PROCESSORS%` so it builds the two projects (mapnik-json;mapnik-wkt) in parallel, but each of them uses only one CL.exe process as there is no `/MP`.
