### ISSUE TITLE
Put ICU_DATA, PROJ_LIB, and GDAL_DATA in mapnik_settings.py

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik-gyp#7]
To allow the python bindings to be easy to set up we need to generate a mapnik_settings.py and have these environment variables set in it, using relative paths.

The mapnik v2.2.0 SDK used something like:

```python
from os import path 
mapnik_data_dir = path.normpath(path.join(__file__,'../../../../../share/')) 
env = { 
    'GDAL_DATA': path.join(mapnik_data_dir, 'gdal'), 
    'PROJ_LIB': path.join(mapnik_data_dir, 'proj') 
} 
__all__ = [env] 
```

**Comment by BergWerkGIS** [comment]
Environment variables get [written into `set-env-vars.bat`](https://github.com/mapnik/mapnik-gyp/blob/d81a9403e875f9829e75707b9f57b55e75d8aa79/build.bat#L693-L701).
